-- phpMyAdmin SQL Dump
-- version 4.0.10.14
-- http://www.phpmyadmin.net
--
-- Host: localhost:3306
-- Generation Time: Feb 21, 2017 at 03:21 AM
-- Server version: 5.5.52-cll-lve
-- PHP Version: 5.6.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `sai_carbohydrates`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `synonyms` varchar(1000) NOT NULL,
  `mf` varchar(255) NOT NULL,
  `mw` varchar(255) NOT NULL,
  `ms` varchar(255) DEFAULT NULL,
  `appearance` varchar(255) NOT NULL,
  `purity` varchar(255) NOT NULL,
  `sor` varchar(255) NOT NULL,
  `casno` varchar(255) NOT NULL,
  `solubility` varchar(255) NOT NULL,
  `watercontent` varchar(255) NOT NULL,
  `storage` varchar(255) NOT NULL,
  `category` varchar(255) NOT NULL,
  `assay_by_hplc` varchar(255) NOT NULL,
  `melting_point` varchar(20) NOT NULL,
  `ph` varchar(20) NOT NULL,
  `dioxane_free` varchar(255) NOT NULL,
  `research` varchar(255) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `usage_product` varchar(255) NOT NULL,
  `application` varchar(255) NOT NULL,
  `identity_ir` varchar(255) NOT NULL,
  `identity_ftir` varchar(255) NOT NULL,
  `transport` varchar(255) NOT NULL,
  `free_phenol` varchar(255) NOT NULL,
  `p_nitro_phenol` varchar(255) NOT NULL,
  `moisture_content` varchar(255) NOT NULL,
  `free_inorganics` varchar(255) NOT NULL,
  `molar_absence` varchar(255) NOT NULL,
  `boiling_point` varchar(20) NOT NULL,
  `others` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=175 ;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `synonyms`, `mf`, `mw`, `ms`, `appearance`, `purity`, `sor`, `casno`, `solubility`, `watercontent`, `storage`, `category`, `assay_by_hplc`, `melting_point`, `ph`, `dioxane_free`, `research`, `description`, `usage_product`, `application`, `identity_ir`, `identity_ftir`, `transport`, `free_phenol`, `p_nitro_phenol`, `moisture_content`, `free_inorganics`, `molar_absence`, `boiling_point`, `others`) VALUES
(1, 'Isopropyl-beta-D-thio galactopyranoside (IPTG)', 'IPTG;<br>Isopropyl-beta-D-thiogalactoside;<br>IPTG, HEMIDIOXANE ADDUCT;<br> ISOPROPYL-1-THIO-BETA-D-GALACTOPYRANOSIDE;<br>ISOPROPYLTHIO-BETA- GALACTOSIDE;ISOPROPYLTHIO -BETA-THIOGALACTOSIDASE; <br>ISOPROPYLTHIO-B-THIOGALACTOPYRANOSIDE;<br>ISOPROPYL THIOGALACTOSIDE;ISOPROPYL-BETA-D-THIOGALACTOPYRANOSIDE, DIOXANE FREE;<br>Isopropyl Î²-D-1 Thiogalactopyranoside; <br>propan-2-yl 1-thio-beta-D-galactopyranoside;<br>1-methylethyl 1-thio-D-galactopyranoside ISOPROPYL-BETA-D-THIOGALACTOPYRANOSIDE (IPTG) DIOXANE FREE', 'C9H18O5S', '238.30', 'Isopropyl-beta-D-thio_galactopyranoside_(IPTG).gif', 'White to off-white crystalline powder', 'Min 99%+', '-31.5 Â± 3.0Â° [a]D20(c=1,H2O)', '367-93-1', 'Soluble in water, and methanol', 'Max 1%', 'Shipped at Ambient Temperature. Store at +2 - 8Â°C.', 'carbohydrates', '98% - 101%   (On Anhydrous Basis)', '110-114â„ƒ', '5.0 - 7.0', 'Not detected', 'Not Intended for Diagnostic or Therapeutic Use.', 'IPTG, Dioxane-Free (isopropyl-Î²-thiogalactoside) is an analogue of allolactose that binds specifically to the repressor protein of thelacoperon and induces expression of Î²-galactosidase inEscherichia coli.The compound is widely used with X-Gal  plates to screen for blue and white colonies. Thelacoperon system and IPTG have been used in multiple cloning experiments and cellular systems to study gene activity.', 'Following reconstitution, aliquot and freeze (-20Â°C). Stock solutions are stable for up to 6 months at -20Â°C. Induces protein synthesis inE. coliwhen transcription is controlled by thelac-promoter. In conjunction with X-gal,q.v.,in detection oflacgene a', 'An analogue of allolactose that binds specifically to the repressor protein of thelacoperon.1. Cho, S., et al. 1985. Biochem. Biophys. Res. Commun. 128: 1268-1273. PMID:3924043 2. Date, T., et al. 1988. Biochemistry. 27: 2983-2990. PMID:3042024 3. Rodrigu', '', '', 'IPTG is the usual abbreviation for isopropyl b-D-thiogalactopyranoside. It is typically produced using D-galactose derived from milk lactose.  manufactures a grade that is of plant origin and therefore does not have the usual TSE/BSE issues. We call this', '', '', '', '', '', '', ''),
(2, '5-BROMO-4-CHLORO-3-INDOLYL-B-D-GALACTOPYRANOSIDE [X-GAL]', '.beta.-D-Galactopyranoside 5-bromo-4-chloro-1H-indol-3-yl;5-Bromo-4-chloro-1H-indol-3- yl beta-D-galactopyranoside;5-Bromo-4-chloro-3-indolyl-.beta. -D-galactoside;5-Bromo-4-chloro-3-indolyl-b-D-galactoside; beta-D-Galactopyranoside, 5-bromo-4-chloro-1H-indol-3-yl;Xgal;X-GAL', 'C14H15BrClNO6', '408.629', '5-BROMO-4-CHLORO-3-INDOLYL-B-D-GALACTOPYRANOSIDE_[X-GAL].gif', 'White to off-white crystalline powder', 'Min 99 %+', '-61.5 Â±3Â° ([Î±]D.20 (c=1,DMF:water,1:1)', '7240-90-6', 'Soluble in DMF (5% w/v) and DMSO (20 mg/ml)', 'Max 0.5%', 'Shipped at Ambient Temperature. Store at +2 - 8Â°C.', 'carbohydrates', '', '', '', '', '', 'Definition of 5-Bromo-4-chloro-3-indoxyl-beta-D-galactopyranoside  An indolyl carbohydrate that is the beta-D-galactoside of 3-hydroxy-1H-indole in which the indole moiety is substituted at positions 4 and 5 by chlorine and bromine, respectively. It is used to test for the presence of an enzyme, beta-galactosidase, which cleaved the glycosidic bond to give 5-bromo-4-chloro-3-hydroxy-1H-indole, which immediately dimerises to give an intensely blue product.', 'For Research Use Only. Not Intended for Diagnostic or Therapeutic Use.', '5-Bromo-4-chloro-3-indoxyl-beta-D-galactopyranoside is used as X-substrate, 5-Bromo-4-chloro-3-indoxyl chromogenic substrate  X-Gal is a chromogenic substrate for beta-galactosidase yielding a blue precipitate. Indicator for coliforms in culturemedia as w', '', '', '', '', '', '', '', '', '', NULL),
(3, '5-BROMO-4-CHLORO-3-INDOLYL-BETA-DGLUCOPYRANOSIDE [X-GLU]', '5-Bromo-4-chloro-3-indoxylglucoside;5-Bromo-4-chloroindol-3-yl-beta-D- glucopyranoside;beta-D-Glucopyranoside, 5-bromo-4-chloro-1H-indol-3-yl; 5-bromo-4-chloro-1H-indol-3-yl beta-D-glucopyranoside;5-bromo-4-chloro- 1H-indol-3-yl beta-L-galactopyranoside;5-Bromo-4-chloro-3-indolyl Î²-D-glucopyranosideCHX', 'C14H15BrClNO6', '408.629', '5-BROMO-4-CHLORO-3-INDOLYL-BETA-DGLUCOPYRANOSIDE_[X-GLU].gif', 'White to off-white crystalline powder', 'Min 99%+', '-81Â° Â± 3Â° [Î±]D.20 (c=1, DMF)', '15548-60-4', 'DMF: 50 mg/mL, clear, colorless to very faintly yellow', 'Max 1%', 'Shipped at Ambient Temperature. Store at +2 - 8Â°C.', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(4, '5-BROMO-6-CHLORO-3-INDOLYL B-D-GLUCURONIDE CYCLOHEXYLAMMONIUM SALT', 'Magenta b-D-GlcA CHX Magenta b-D-glucuronide CHX', 'C14H13BrClNO7.C6H13N', '521.79', '5-BROMO-6-CHLORO-3-INDOLYL_B-D-GLUCURONIDE_CYCLOHEXYLAMMONIUM_SALT.gif', 'White to off-white crystalline powder', 'Min 99%+', '-68 Â± 3.0Â° [a]D20(c=1,DMF/H2O 1:1)', '144110-43-0', 'Solution (1% in DMF)', 'Max 1%', 'Shipped at Ambient Temperature. Store at +2 - 8Â°C.', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(5, '5-Bromo-4-chloro-3-indoxyl-beta-D-glucuronic acid, Sodium salt Tri Hydrate (X-GLUC Sodium Salt.)', 'X-b-D-Glucuronide, X-b-D-GLcA-Na BCI-BETA-D-GLUCURONIDE, SODIUM SALT;BCI-GLUCURO, SODIUM SALT;BCIG SODIUM SALT;BC-INDICATOR;5-BROMO-4-CHLORO-3-INDOLYL-BETA-D-GLUCURONIC ACID SODIUM SALT;5-BROMO-4-CHLORO-3-INDOLYL-BETA-D-GLUCURONIC ACID;5-BROMO-4-CHLORO-3-INDOLYL-BETA-D-GLUCURONIDE NA SALT;5-BROMO-4-CHLORO-3-INDOXYL-BETA-D-GLUCURONIC ACID, SODIUM SALT', 'C14H12BrClNNaO7', '444.59', '5-Bromo-4-chloro-3-indoxyl-beta-D-glucuronic_acid__Sodium_salt_Tri_Hydrate_(X-GLUC_Sodium_Salt.).png', 'White to off-white crystalline powder', 'Min 98%', '-99.0 Â± 3.0    [Î±]D.25 (c=1, DMF:H2O, 1:1)', '370100-64-4  (or) 129541-41-9', '(1% in water)Clear and practically colourless solution', '9.0% Â± 2.0%', 'Shipped at Ambient Temperature. Store at +2 - 8Â°C.', 'carbohydrates', 'Min 98%', '', '', '', 'Not Intended for Diagnostic or Therapeutic Use.', 'References:  Bauer, R., et al., Functional expression of bacterial Î²-glucuronidase and its use as a reporter system in the yeast Yarrowia lipolytica.. Yeast 9, 71-75, (1993) Schmitz, U.K., et al., Application of the Î²-glucuronidase gene fusion system to Saccharomyces cerevisiae.. Curr. Genet. 17, 261-264, (1990) Daniell, H., Foreign gene expression in chloroplasts of higher plants mediated by tungsten particle bombardment. Meth. Enzymol. 217, 536-556, (1993)', '', 'A chromogenic substrate for Î²-glucuronidase gene detection   XGLUC Cyclohexylammonium Salt is a Chromogenic substrate for Î²- glucuronidase (GUS) gene detection', '', '', '', '', '', '', '', '', '', NULL),
(6, '5-Bromo-6-chloro-3-indolyl-b-D-glucuronide cyclohexylammonium salt (Magenta-Î²-D-glucuronide cyclohexylammonium salt)', 'MAGENTA(TM)-BETA-D-GLUCURONIDE CYCLOHEXYLAMMONIUM SALT;MAGENTA(TM)-BETA-D-GLCA CHX;MAGENTAR-BETA-D-GLUCURONIDE, CYCLOHEXYLAMMONIUM SALT;MAGENTA-BETA-D-GLCA;MAGENTA-BETA-D-GLUCURONIDE CHX-SALT;MAGENTA GLCA CYCLOHEXYLAMMONIUM SALT;MAGENTA-GLUCURO CHA SALT;MAGENTA GLUCURONIDE, Magenta-beta-D-glucuronide cyclohexylammonium salt; Magenta-beta-D-glucuronide Â· CHX-salt', 'C14H13BrClNO7Â·C6H13N', '521.79', '5-Bromo-6-chloro-3-indolyl-b-D-glucuronide_cyclohexylammonium_salt_(Magenta-Î²-D-glucuronide_cyclohexylammonium_salt).gif', 'White to off-white crystalline powder', 'Min 99%+', '-68 Â± 3.0Â°  [a]D20(c=1,DMF/H2O  1:1)', '144110-43-0', 'Solution (1% in DMF)', 'Max 1%', 'Shipped at Ambient Temperature. Store at +2 - 8Â°C.', 'carbohydrates', '', '', '', '', 'Not Intended for Diagnostic or Therapeutic Use.', 'TLC (50 mg in 1.5 ml of acetic acid; butanol/acetic acid/water 6:3:2; UV 254 nm, sulfuric acid)', 'Purity (TLC) (50 mg in 1.5 ml of acetic acid; butanol/acetic acid/water 6:3:2; UV 254 nm, sulfuric acid)', 'Application Test (enzymatic test with betaglucuronidase)  an intense magenta color (lambda max.: 565 nm)', 'Conforms to structure', '', '', '', '', '', '', '', '', NULL),
(7, '2,3,4,6-TETRA-O-ACETYL-Î‘-D-GALACTOPYRANOSYL BROMIDE', '', '', '', NULL, '', '', '', '3068-32- 4', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(8, '2,3,4,6-TETRA-O-ACETYL-A-D-GLUCOPYRANOSYL CHLORIDE', '', '', '', NULL, '', '', '', '4451-35-8', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(9, '1,2,3,4-TETRA-O-ACETYL-Î’-D-GLUCURONIDE METHYL ESTER', '', '', '', NULL, '', '', '', '7355-18-2', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(10, '5-Bromo indoxyl-1,3-diacetate', '1-acetyl-5-bromo-1h-indol-3-oacetate(ester);1-Acetyl-5-bromo-1H-indol-3-yl acetate;-Bromoindoxyl acetate;1-ACETYL-5-BROMOINDOL-3-OL ACETATE;5-BROMOINDOXYL-1,3-DIACETATE;5-BROMOINDOXYL DIACETATE;ACETIC ACID 1-ACETYL-5-BROMO-1H-INDOL-3-YL ESTER;3-Acetoxy-1-acetyl-5-bromoindole', 'C12H10BrNO3', '296.12', '5-Bromo_indoxyl-1_3-diacetate.gif', 'Light yellow to brown color powder', 'Min 97%', '', '33588-54-4', '', 'Max 1%', '', 'carbohydrates', '', '125-128 Â°C(lit.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(12, 'D-Gulonic acid-1,4-lactone  ( D-Gulonolactone )', 'D-Gulonic acid-1,4-lactone  ( D-Gulonolactone ) ; D-Gulonicacid''-lactone; D-Gulono-1,4-lactone; D-(-)-Gulono-1,4-lactone', 'C6H10O6', '178.14', 'D-Gulonic_acid-1_4-lactone__(_D-Gulonolactone_).png', 'White to off-white crystalline powder', 'Min 98 %', '[Î±]20/D -52 to âˆ’58Â°, c = 4 in H2O', '6322-07-2', '', 'Max 1 %', '', 'carbohydrates', '', '182-188 Â°C(lit.)', '', '', '', '', '', '', 'Conforms to structure', '', '', '', '', '', '', '', '', NULL),
(13, '5-Bromo-4-chloro-3-indolyl 2-acetamido-2-deoxy-b-D-glucopyranoside (5-Bromo-4-chloro-3-indolyl N-acetyl-b-D-glucosaminide) (X-GlcNAc )', '5-Bromo-4-chloro-3-indoxyl-2-acetamido-2-deoxy- Î²-D-glucopyranoside (X-Î²-D-GlcNAc), 5-Bromo-4-chloro-3-indolyl N-acetyl-b-D-glucosaminide X-GlcNAc, X-BETA-D-GLCNAC;X-GLUNAC;X-GLCNAC;X-N-ACETYL-GLUCOSAMINIDE;X-N-ACETYL-BETA-D-GLUCOSAMINIDE;5-BROMO-4-CHLORO-3-INDOLYL-N-ACETYL-BETA-D-GLUCOSAMINIDE;5-BROMO-4-CHLORO-3-INDOLYL 2-ACETAMIDO-2-DEOXY-BETA-D-GLUCOPYRANOSIDE;5-BROMO-4-CHLORO-3-INDOXYL-N-ACETYL-BETA-D-GLUCOSAMINIDE', 'C16H18BrClN2 O6', '449.69', '5-Bromo-4-chloro-3-indolyl_2-acetamido-2-deoxy-b-D-glucopyranoside_(5-Bromo-4-chloro-3-indolyl_N-acetyl-b-D-glucosaminide)_(X-GlcNAc_).gif', 'White to off-white crystalline powder', 'Min 98%', '71.0 to -65.0     [alpha]D (c = 1 in methanol, on dry matter)', '4264-82-8', 'Practically colorless, clear  , (5% in DMF) , (1% in methanol)', 'Max 4%', 'Shipped at Ambient Temperature. Store at +2 - 8Â°C.', 'carbohydrates', '', '246-248â„ƒ', '', '', 'Not Intended for Diagnostic or Therapeutic Use.', '', 'Can be used as a chromogenic substrate for N-Acetyl-Î²-D-glucosaminidase, yielding a blue precipitate. It is also used in histochemistry.', '5-Bromo-4-chloro-3-indoxyl-N-acetyl-beta-D-glucosaminide is used as X-substrate, 5-Bromo-4-chloro-3-indoxyl chromogenic substrate  Chromogenic substrate for N-Acetyl-beta-D-glucosaminidase yielding a blue precipitate. Contained in certain mycologicalcultu', 'Conforms to structure', '', '', '', '', '', '', '', '', NULL),
(14, '5-BROMO-6-CHLORO-3-INDOLYL CAPRYLATE , ( Magenta Caprylate)', '', '', '', NULL, '', '', '', '209347-94-4', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(15, '5-Bromo-6-chloro-3-indolyl-beta-D-glucopyranoside [ Magenta-beta-D-glucoside ] (Red Glucose)', '', '', '', NULL, '', '', '', '93863-89-9', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(16, '6-chloro-3-indolyl-beta-D-galactopyranoside [ Salmon Gal ] [ Rose gal ]', '6-Chloro-3-indolyl--D-galactopyranoside;Red-Gal(or) 6-Chloro-3-indolyl-  D-galactoside;ChloroindolylDgalactopyranoside;Salmon Galactoside;  6-chloro-1H-indol-1-yl beta-D-galactopyranoside;6-chloro-1H-indol-3-yl  Î²-D-galactopyranoside, Salmon Gal ,Rose gal, 6-Chloro-3-(b-D-galactopyranosyloxy)indole', 'C14H16ClNO6', '329.7', '6-chloro-3-indolyl-beta-D-galactopyranoside_[_Salmon_Gal_]_[_Rose_gal_].gif', 'Off-white to pale pink powder', 'Min 99%+', '-40.0 to -50.0Â°   [Î±]D.20 (c=1, MeOH)', '138182-21-5', 'Soluble in 5% (w/v) Methanol,Colorless to slightly yellowish, clear', 'Max 1%', 'Shipped at Ambient Temperature. Store at +2 - 8Â°C.', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(17, '6-chloro-3-indolyl-beta-D-gluco pyranoside [ Salmon glu ] [ Rose glu ]', '', '', '', NULL, '', '', '', '159954-28-6', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(18, '5-Bromo-3-indolyl-b-D-galactopyranoside (Blue Gal ) ( Bluo-Gal)', '', '', '', NULL, '', '', '', '97753-82-7', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(19, '4-Chloro-3-indolyl b-D-galactopyranoside', '', '', '', NULL, '', '', '', '135313-63-2', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(20, 'D-Glucoronic acid sodium salt', '', '', '', NULL, '', '', '', '14984-34-0', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(21, 'D-Glucoronic acid', '', '', '', NULL, '', '', '', '6556-12-3', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(22, '1,2,3,4-tetra-o-acetyl glucoronic acid methyl ester', '', '', '', NULL, '', '', '', '62133-77-1', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(23, '1,2,3,4,6-Penta-O-acetyl-Î²-D-galactopyranoside ( beta-D-Galactose pentaacetate)', '', '', '', NULL, '', '', '', '4163-60-4', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(24, '1,2,3,4,6-Penta-O-acetyl-Î±-D-galactopyranoside (alfa-D-Galactose pentaacetate)', '', '', '', NULL, '', '', '', '4163-59-1', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(25, '1,2,3,4,6-Penta-O-acetyl-Î²-D-glucopyranoside ( beta- D-Glucose pentaacetate)', '', '', '', NULL, '', '', '', '604-69-3 (or) 154395-36-5', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(26, '1,2,3,4,6-Penta-O-acetyl-Î±-D-glucopyranoside (Î±-D-Glucose pentaacetate)', '', '', '', NULL, '', '', '', '604-68-2', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(27, '4-Methyl umbelliferyl-beta-D-glucoronide tri hydrate (MUG) (4-MUG) (Mug-glucoronide)', '', '', '', NULL, '', '', '', '6160-80-1', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(28, '4-Methylumbelliferyl Î²-D-galactopyranoside (Mug-gal)', '', '', '', NULL, '', '', '', '6160-78-7', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(29, '4-Methylumbelliferyl-Î²- D-glucopyranoside (Mug-glucoside)', '', '', '', NULL, '', '', '', '18997-57-4', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(30, '2-Nitro phenyl-beta-D-galactopyranoside (ONPG)', '', '', '', NULL, '', '', '', '369-07-3', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(31, '4-Nitro phenyl-beta-D-galactopyranoside, (PNPG)', '', '', '', NULL, '', '', '', '3368-04-5', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(32, 'Phenyl-Î²-D-galactopyranoside', '', '', '', NULL, '', '', '', '2818-58-8', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(33, 'Ethyl 1-thio-beta-D-glucopyranoside', '', '', '', NULL, '', '', '', '7473-36-1', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(34, 'Ethyl 1-thio-beta-D-galactopyranoside', '', '', '', NULL, '', '', '', '56245-60-4', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(35, 'n-Octyl-Î²-D-Galactopyranoside', '', '', '', NULL, '', '', '', '40427-75-6', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(36, 'n-Octyl-Î²-D-Glucopyranoside', '', '', '', NULL, '', '', '', '00-0-0', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(37, '2, 3, 4, 6-tetra-o-acetyl-beta-D-glucopyranosyl isothiocyanate', '', '', '', NULL, '', '', '', '14152-97-7', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(38, 'D-Glucuronolactone (D-Glucurono-3,6-lactone) ( D-(+)-Glucuronic acid Î³-lactone)', '', '', '', NULL, '', '', '', '32449-92-6', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(39, 'Methyl b-D-glucopyranoside hemihydrates', '', '', '', NULL, '', '', '', '7000-27-3', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(40, '1,2:5,6-di-O-isopropylidene-D-mannitol', '', '', '', NULL, '', '', '', '1707-77-3', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(41, '3,4-O-isopropylidene-D-mannitol', '', '', '', NULL, '', '', '', '3969-84-4', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(42, '1,2,3,4,5,6-tri-O-isopropylidene-D-mannitol', '', '', '', NULL, '', '', '', '3969-59-3', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(43, '1,6-Anhydro-Beta-D-Glucose', '', '', '', NULL, '', '', '', '498-07-7', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(44, '5-Bromo-4-chloro-3-indolyl acetate', '', '', '', NULL, '', '', '', '3252-36-6', '', '', '', 'carbohydrates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(45, 'Phenyl phosphate disodium salt hydrate', 'Disodiumphenylphosphate,dihy;Phosphoricacid,monophenylester,disodiumsalt; DISODIUM PHENYL-(O)-PHOSPHATE;DI-SODIUM PHENYL PHOSPHAT DIHYDRATE; DISODIUM PHENYLPHOSPHATE;PHENYLPHOSPHORIC ACID DISODIUM SALT;PHENYL PHOSPHATE DISODIUM SALT;PHENYL DISODIUM PHOSPHATE', 'C6H9Na2O6P', '254.0854', 'Phenyl_phosphate_disodium_salt_hydrate.png', 'White to Off White Powder', 'NLT. 99 %', '', '3279-54-7', 'Freely soluble in water', '11 % to 17.1 %', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(46, '1-Naphthyl phosphate monosodium salt monohydrate', 'Î±-Naphthyl phosphate monosodium salt monohydrate, Sodium 1-naphthyl phosphate monohydrate  ALPHA-NAPHTHYL ACID PHOSPHATE, SODIUM SALT;ALPHA-NAPHTHYL PHOSPHATE  MONOSODIUM SALT MONOHYDRATE;ALPHA-NAP-PHOS NA H2O;1-NAPHTHYL PHOSPHATE  MONOSODIUM SALT MONOHYDRATE;1-NAPHTHYLPHOSPHORIC ACID  MONOSODIUM SALT  MONOHYDRATE;1-NAPHTHYL PHOSPHATE SODIUM SALT, MONOHYDRATE; SODIUM 1-NAPHTHYL  HYDROGEN PHOSPHATE MONOHYDRATE;SODIUM ALPHA-NAPHTHYL ACID PHOSPHATE  (MONOSODIUM) MONOHYDRATE', 'C10H7OP(O)(OH)(ONa) Â· H2O', '264.15', '1-Naphthyl_phosphate_monosodium_salt_monohydrate.gif', 'White to Off White Powder', 'NLT. 98 %', '', '81012-89-7', 'Freely soluble in water', '5 % to 10 %', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(47, '1-Naphthyl phosphate Disodium salt', 'PHOSPHORIC ACID 1-NAPHTHYL ESTER DISODIUM SALT;SODIUM A-NAPHTHYL ACID  PHOSPHATE (DISODIUM);1-NAPHTHYLPHOSPHORIC ACID DISODIUM SALT;1-NAPHTHYL  PHOSPHATE DISODIUM SALT;1-NAPHTHYL DISODIUM ORTHOPHOSPHATE;1-NAPHTHALENOL  DIHYDROGEN PHOSPHATE DISODIUM SALT;ALPHA-NAP-PHOS 2NA;ALPHA-NAPHTHYL  PHOSPHATE DISODIUM SALT', 'C10H7Na2O4P', '268.11', '1-Naphthyl_phosphate_Disodium_salt.gif', 'White to Off White Powder', 'NLT. 98 %', '', '2183-17-7', 'Freely soluble in water', '1 %', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(48, '1-Naphthyl phosphate', 'A-NAPHTHYL PHOSPHATE;ALPHA-NAPHTHYL PHOSPHATE;ALPHA-NAPHTHYL  ACID PHOSPHATE;1-NAPHTHYL PHOSPHATE;AURORA KA-1621;  ~-Naphthyl phosphate 1-Naphthyl phosphate;naphthyl dihydrogen phosphate;  1-NAPHTHYL PHOSPHATE 99+%', 'C10H9O4P', '224.15', NULL, 'White to Off White Powder', 'NLT. 98 %', '', '1136-89-6', 'Freely soluble in water', '1 %', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(49, '4â€“NITRO PHENYL PHOSPHATE DI SODIUM SALT HEXAHYDRATE (PNPP)', '4-Nitrophenyl phosphate disodium salt hexahydrate;4-Nitrophenyl phosphate,  disodium salt hexahydrate;Disodium 4-nitrophenyl phosphate hexahydrate;  Phosphoric acid, 4-nitrophenyl ester, sodium salt, hydrate (1:2:6);  p-Nitrophenyl phosphate disodium hexahydrate;p-Nitrophenyl phosphate,  disodium salt, hexahydrate;pNPP disodium hexahydrate;pNPP disodium  salt hexahydrate;p-NPP, disodium salt, hexahydrate;Sodium 4-nitrophenyl  phosphate hydrate (2:1:6)', 'C6H16NNa2o12P', '371.144', '4â€“NITRO_PHENYL_PHOSPHATE_DI_SODIUM_SALT_HEXAHYDRATE_(PNPP).gif', 'Off White To Pale Yallow crystalyne powder', 'NLT. 99 %', '', '4264-83-9 or 333338-18-4', 'Freely soluble in water', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(50, 'Bis(p-nitrophenyl) phosphate sodium salt', 'BIS(P-NITROPHENYL) PHOSPHATE SODIUM SALT;BIS(PNP)-PHOS NA;  BIS(4-NITROPHENYL)PHOSPHORIC ACID SODIUM SALT;  BIS(4-NITROPHENYL)PHOSPHATE SODIUM SALT;  SODIUM BIS(4-NITROPHENYL)PHOSPHATE  ;bis(P-nitrophenyl)phosphate sodium;Sodium Bis(4-nitrophenyl)  phosphate [for Phosphodiesterase Substrate];Bis(4-nitrophenyl)=sodium phosphate', 'C6H16NNa2o12P', '362.16', NULL, 'Off White To Pale Yallow crystalyne powder', 'NLT. 98 %', '', '4043-96-3', 'Freely soluble in water', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(51, '1-Naphthyl phosphate Potassium salt', 'Naphthyl POTASSIUM PHOSPHATE SALT-1 ; ALPHA-Naphthyl Monopotassium  the ACID PHOSPHATE SALT ; the A-naphthyl acid phosphate monopotassium ;   [alpha]-naphthyl acid phosphate monopotassium Salt', 'C10H7OP(O)(OH)(OK)', '262.24', '1-Naphthyl_phosphate_Potassium_salt.gif', 'Off White To yallow color powder', 'NLT. 98 %', '', '100929-85-9', 'Freely soluble in water', '1 %', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(52, '4-NITROPHENYL PHOSPHATE BIS[TRIS(HYDROXYMETHYL)AMINOMETHANE] SALT', '4-Nitrophenylphosphoric acid di[tris(hydroxymethyl)aminomethane] salt;  4-nitrophenyl dihydrogen phosphate - 2-amino-2-(hydroxymethyl)propane-1,3-diol (1:2)  4-NITROPHENYLPHOSPHORIC ACID BIS[TRIS(HYDROXYMETHYL)METHYLAMINE]  SALT;4-NITROPHENYLPHOSPHORIC ACID DI[TRIS(HYDROXYMETHYL)AMINOMETHANE]  SALT;4-NITROPHENYL PHOSPHATE BIS[TRIS(HYDROXYMETHYL)AMINOMETHANE] SALT;  4-NITROPHENYL PHOSPHATE DITRIS;4-NITROPHENYL PHOSPHATE DI(TRIS) SALT;  P-NITROPHENYL PHOSPHATE DI(TRIS) SALT;PNPP-TRIS;PNPP, 2TRIS', 'C14H28N3O12P', '461.358', '4-NITROPHENYL_PHOSPHATE_BIS[TRIS(HYDROXYMETHYL)AMINOMETHANE]_SALT.gif', 'Off White To Pale Yallow crystalyne powder', 'NLT. 99 %', '', '68189-42-4', 'Freely soluble in water', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(53, '4-NITROPHENYL PHOSPHATE BIS(CYCLOHEXYLAMMONIUM) SALT', '4-Nitrophenyl phosphate bis(cyclohexylammonium) salt;4-nitrophenyl dihydrogen  phosphate - cyclohexanamine (1:2);dicyclohexanaminium 4-nitrophenyl phosphate hydrate;  p-Nitrophenylphosphate, dicyclohexylammonium salt', 'C18H34N3O7P', '435.45', '4-NITROPHENYL_PHOSPHATE_BIS(CYCLOHEXYLAMMONIUM)_SALT.gif', 'Off White To Pale Yallow crystalyne powder', 'NLT. 99 %', '', '52483-84-8', 'Freely soluble in water', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(54, '4-Nitrophenyl phosphate magnesium salt', '', '', '', NULL, '', '', '', '32348-90-6', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(55, '4-Nitrophenyl phosphate bis(2-amino- 2-ethyl-1,3-propanediol) salt', '', '', '', NULL, '', '', '', '62796-28-5', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(56, '4-Nitrophenyl phosphate', '', '', '', NULL, '', '', '', '330-13-2', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(57, '5-Bromo-4-chloro-3-indolyl phosphate di sodium salt [X-phosphate di sodium salt] [ BCIP di sodium salt ]', '', '', '', NULL, '', '', '', '102185-33-1', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(58, '5-Bromo-4-chloro-3-indolyl phosphate ptoluidine salt [X-phosphate p-toluidine Salt] [ BCIP ptoluidine salt ]', '', '', '', NULL, '', '', '', '6578-06-9', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(59, '5-Bromo-6-chloro-3-indolyl phosphate di sodium salt [ Magenta-phosphate di soduim salt ]', '', '', '', NULL, '', '', '', '404366-59-2', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(60, '5-Bromo-6-chloro-3-indolyl phosphate ptoluidine Salt [ Magenta-phosphate p-toluidine Salt ]', '', '', '', NULL, '', '', '', '6769-80-8', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(61, '6-CHLORO-3-INDOLYL PHOSPHATE P-TOLUIDINE SALT (Salmon-phosphate p-toluidine salt)', '', '', '', NULL, '', '', '', '159954-33-3', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(62, '5-Bromo-3-indolyl phosphate p-toluidine salt', '', '', '', NULL, '', '', '', '80008-69-1', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(63, '5-Bromo-3-indolyl phosphate disodium salt (Blue-phos)', '', '', '', NULL, '', '', '', '16036-59-2', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(64, '4-Methylumbelliferyl phosphate disodium salt trihydrate', '', '', '', NULL, '', '', '', '22919-26-2', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(65, 'Phenyl phosphate disodium salt hydrate', '', '', '', NULL, '', '', '', '3279-54-7', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(66, 'dibenzyl phosphate', '', '', '', NULL, '', '', '', '1623-08-1', '', '', '', 'phosphates', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(67, '2-BROMOETHYL-4-NITROPHENYL ETHER', '1-(2-BROMOETHOXY)-4-NITROBENZENE;2-(4-Nitrophenoxy)ethyl bromide  2-(4-Nitrophenoxy)-1-bromoethane;2-Bromoethyl-4-nitrophenyl Ether;b-Bromo-4-nitrophenetole;', 'C8H8BrNO3', '246.06', '2-BROMOETHYL-4-NITROPHENYL_ETHER.jpg', 'Off white to pale yallow crystalyne powder', 'Min. 97%', '62.0 to 67.0 deg-C', '13288-06-7', 'Soluble in Chloroform, Dichloromethane, Ethyl Acetate and Methanol', 'Max 1%', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(68, '4-Nitrophenol', '', '', '', NULL, '', '', '', '100-02-7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(69, '4-Nitrophenyl sulfate potassium salt', '', '', '', NULL, '', '', '', '6217-68-1', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(70, '5-Bromo-4-chloro-3-indolyl sulfate potassium salt', '', '', '', NULL, '', '', '', '6578-07-0', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(71, '2-Amino-4-methoxy-benzoic acid', '', '', '', NULL, '', '', '', '4294-95-5', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(72, 'Indoxyl 1,3-diacetate', '1,3-Diacetoxyindole ; INDOXYL 1,3-DIACETATE;1,3-DIACETOXYINDOLE;ACETIC ACID 1-ACETYL-1H-INDOL-3-YL ESTER;AKOS AU36-M367;AKOS 92481;N-ACETYLINDOL-3-YL ACETATE;N-ACETYL-3-ACETOXYINDOLE;1-acetyl-1h-indol-3-oacetate(ester) ; 1-[3-(Acetyloxy)-1H-indol-1-yl]ethanone 1,3-Diacetylindoxyl, indoxyl-1,3-diacetate 1-Acetylindol-3-yl acetate', 'C12H11NO3', '217.23', 'Indoxyl_1_3-diacetate.gif', '39GwAQ7PeH7fJTFa4DXguurfn7GULq2pTs', 'Min 97%', '', '16800-67-2', '', 'Max 1%', '', 'carbohydrates', '', '', '', '', 'Onyeibor, O., et al., J. Med. Chem., 48, 2701 (2005)', 'Chen, J., et al., Bioorg. Med. Chem., 8, 2461 (2000)', '', '3-Indoxyl-1,3-diacetate is used as Y-substrate, 3-Indoxyl chromogenic substrate', '', '', '', '', '', '', '', '', '', NULL),
(74, '5-Bromo-4-chloro indoxyl-1,3-diacetate ; (x-diacetate)', '1-acetyl-5-bromo-4-chloro-1h-indol-3-oacetate(ester);5-BROMO-4-CHLORO-3-INDOLYL-1,3-DIACETATE;3 ACETOXY-1-ACETYL-5-BROMO-4-CHLOROINDOLE;5-BROMO-4-CHLOROINDOXYL-1,3-DIACETATE;ACETIC ACID-(1-ACETYL-5-BROMO-4-CHLORO-1H-INDOL-3-YL) ESTER;1-ACETYL-5-BROMO-4-CHLORO-1H-INDOL-3-YL ACETATE;N-ACETYL-5-BROMO-4-CHLOROINDOL-3-YL ACETATE;5-BROMO-4-CHLOROINDOXYL 1,3-DIACETATE, Ethanone,1-[3-(acetyloxy)-5-bromo-4-chloro-1H-benzazole-1-yl] ; x-diacetate.', 'C12H9BrClNO3', '330.56', '5-Bromo-4-chloro_indoxyl-1_3-diacetate_;_(x-diacetate).gif', 'Yellow â€“ yellowish brown Crystalline', 'Min 98%', '', '3030-06-6', 'Soluble in Acetic acid and Ethyl acetate', 'Max 1.0%', '', 'finechemicals', '', '164-168â„ƒ', '', '', '', '', '', '', 'Conforms to structure', '', '', '', '', '', '', '', '', NULL),
(75, '5-Bromo-6-chloro indoxyl-1,3-diacetate  (Magenta Diacetate)', 'magenta indole, ACETIC ACID 1-ACETYL-5-bromo-6-CHLORO-1H-INDOL-3-YL ESTER; 5-bromo6-CHLOROINDOLYL-1,3-DIACETATE;1-acetyl-5-bromo-6-chloro-1H-indol-3-yl acetate', 'C12H9BrClNO3', '330.57', '5-Bromo-6-chloro_indoxyl-1_3-diacetate__(Magenta_Diacetate).gif', 'Yellow â€“ yellowish brown Crystalline', 'Min  98 %', '', '108847-96-7', 'Soluble in Acetic acid and Ethyl acetate', 'Max 1 %', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(76, '6-Chloro indoxyl-1,3-diacetate ( salmon Diacetate) ( Rose Diacetate)', 'ACETIC ACID 1-ACETYL-6-CHLORO-1H-INDOL-3-YL ESTER;6-CHLOROINDOLYL-1,3-DIACETATE;1-acetyl-6-chloro-1H-indol-3-yl acetate, 6-CHLOROINDOXYL-1,3-DIACETATE;ACETIC ACID 1-ACETYL-6-CHLORO-1H-INDOL-3-YL ESTER;6-CHLOROINDOLYL-1,3-DIACETATE', 'C12H10ClNO3', '251.66', '6-Chloro_indoxyl-1_3-diacetate_(_salmon_Diacetate)_(_Rose_Diacetate).gif', 'Yellow â€“ yellowish brown Crystalline', 'Min 98 %', '', '108761-33-7', 'Soluble in Acetic acid and Ethyl acetate, MDC', 'Max 1 %', '', 'finechemicals', '', '', '', '', '', '', '', '', 'Conforms to structure', '', '', '', '', '', '', '', '', NULL),
(77, '4-Chloro indoxyl-1,3-diacetate', '', 'C12H10ClNO3', '251.67', '4-Chloro_indoxyl-1_3-diacetate.jpg', 'Cystalline powderr', 'Min 97%', '', '109014-54-2', 'Soluble in Ethyl acetate & acetic acid', 'Max 1 %', '', 'finechemicals', '', '125-129 Â°C', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(78, '1-Acetyl-5-bromo-6-chloro-1H-indol-3-ol', '', '', '', NULL, '', '', '', '90766-88-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(79, '1-Acetyl-5-bromo-4-chloro-1H-indol-3-ol', 'X-1-acetate; 1-Acetyl-5-bromo-4-chloro-1H-indol-3-ol ; N-Acetyl-5-bromo-4-chloro-3-hydroxy-1H-indole ; X-1-ACETATE;5-BROMO-4-CHLORO-3-INDOXYL-1-ACETATE;5-Bromo-4-chloro-3-indolyl-1-acetate;1H-Indol-3-ol, 1-acetyl-5-bromo-4-chloro-;1-(5-broMo-4-chloro-3-hydroxyindol-1-yl)ethanone;N-Acetyl-5-broMo-4-chloro-3-hydroxy-1H-indole, X-1 acetate', 'C10H7BrClNO2', '288.53', '1-Acetyl-5-bromo-4-chloro-1H-indol-3-ol.gif', 'Yellow to Brown color powder', 'Min 98%', '', '125328-76-9', '5% Sodium hydroxide solution', 'Max 1%', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(80, '2-Hydroxy-6-methoxybenzaldehyde', '', '', '', NULL, '', '', '', '700-44-7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(81, '4-tert-Butylcalix[4]arene', '', '', '', NULL, '', '', '', '60705-62-6', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(82, '3-furaldehyde', '', '', '', NULL, '', '', '', '498-60-2', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(83, '3-phenyl pyridine', '', '', '', NULL, '', '', '', '1008-88-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(84, 'antraquinon-2-carboxylic acid', '', '', '', NULL, '', '', '', '117-78-2', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(85, '2,3-diamino benzoic acid methyl ester', '', '', '', NULL, '', '', '', '107582-20-7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(86, '3-nitro phthalamic anhydride', '', '', '', NULL, '', '', '', '641-70-3', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(87, '3-nitro phthalamic acid', '', '', '', NULL, '', '', '', '77326-45-5', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(88, '3,6-pyridazine diol', '', '', '', NULL, '', '', '', '92335-53-0', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(89, '3,6-di chloro pyridazine', '', '', '', NULL, '', '', '', '141-30-0', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(90, '4-bromo-2-methyl-6-nitro aniline', '', '', '', NULL, '', '', '', '77811-44-0', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(91, '2-amino-3-nitro toluene', '', '', '', NULL, '', '', '', '570-24-1', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(92, '5-hydroxy-3,4-dihydrocarbostyril', '', '', '', NULL, '', '', '', '30389-33-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(93, '2-methyl benzoic acid ethyl ester', '', '', '', NULL, '', '', '', '87-24-1', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(94, '2-METHYLBENZOIC ACID', '', '', '', NULL, '', '', '', '118-90-1', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(95, '3,3-diphenyl propio nitril', '', '', '', NULL, '', '', '', '2286-54-6', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(96, 'Cinnamo nitrile', '', '', '', NULL, '', '', '', '1885-38-7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(97, '2-chloro-3-nitro toluene', '', '', '', NULL, '', '', '', '3970-40-9', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(98, '2-amino-3-nitro toluene', '', '', '', NULL, '', '', '', '570-24-1', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(99, '5-bromo indole', '', '', '', NULL, '', '', '', '10075-50-0', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(100, 'potassium HMDS', '', '', '', NULL, '', '', '', '40949-94-8', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(101, 'beta-alanine', '', '', '', NULL, '', '', '', '107-95-9', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(102, 'Benzophenone imine', '', '', '', NULL, '', '', '', '1013-88-3', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(103, 'Methyl-2-chloro benzoate', '', '', '', NULL, '', '', '', '610-96-8', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(104, '4-ISOPROPOXY BENZALDEHYDE', '', '', '', NULL, '', '', '', '18962-05-5', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(105, '3-FUROIC ACID', '', '', '', NULL, '', '', '', '488-93-7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(106, '3-(2-FURYL)ACRYLIC ACID', '', '', '', NULL, '', '', '', '539-47-9', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(107, '3,3-DIPHENYLPROPIONITRILE', '', '', '', NULL, '', '', '', '2286-54-6', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(108, 'sodium phenoxide', '', '', '', NULL, '', '', '', '139-02-6', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(109, '4-Chloropyridine hydrochloride', '', '', '', NULL, '', '', '', '7379-35-3 - 1', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(110, '2-amino-6-chlorobenzoic acid', '', '', '', NULL, '', '', '', '2148-56-3', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(111, '2,4-Dichlorobenzoic acid', '', '', '', NULL, '', '', '', '50-84-0', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(112, '5-Nitroindole', '', '', '', NULL, '', '', '', '6146-52-7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(113, '4-METHYL UMBELLIFERONE [ 7-HYDROXY-4-METHYLCOUMARIN]', '', '', '', NULL, '', '', '', '90-33-5', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(114, '5,8-DIHYDRO-1-NAPHTHOL', '', '', '', NULL, '', '', '', '27673-48-9', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(115, '4-Bromo-7-azaindole', '4-Bromo-1H-pyrrolo[2,3-b]pyridine, 1H-PYRROLO[2,3-B]PYRIDINE, 4-BROMO-;4-BROMO-7-AZAINDOLE;4-BROMO-1H-PYRROLO[2,3-B]PYRIDINE;4-broMo-1H-pyrrolo[2;4-BroMo-7-Azaindol;4-Bromo-1H-pyrrolo-[2,3]pyridine;348640-06-2', 'C7H5BrN2', '197.03', '4-Bromo-7-azaindole.png', 'Yellow to Orange powder', 'Min 96%', '', '348640-06-2', '', 'Max 1 %', '', 'finechemicals', '', '178-183 Â°C', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(116, '4-CHLOROBUTYL VERATRATE (3,4-Dimethoxybenzoic acid 4-chlorobutyl ester)', 'W-ChlorobutylVeratrate;4-CHLOROBYTYL VERATRATE CAS NO.:;4-chlorobutyl veratrate;3,4-Dimethoxybenzoic acid 4-chlorobutyl ester;Veratric acid 4-chlorobutyl ester;4-Chlorobutyl 3,4-diMethoxybenzoate;Benzoic acid,3,4-diMethoxy-, 4-chlorobutyl ester', 'C13H16ClO4', '271.71', '4-CHLOROBUTYL_VERATRATE_(3_4-Dimethoxybenzoic_acid_4-chlorobutyl_ester).png', 'Brown color viscous liquid', 'Min 98 %+', '', '69788-75-6', 'poorly miscible in water, miscible in methanol', 'Max. 1.0% w/w', '', 'finechemicals', '', '', '', '', '', '', '4-chlorobutyl 3,4-dimethoxybenzoate, Intermediates of Mebeverine,Intermediate of Mebeverine,Mebeverine intermediates,, Cas no 69788-75-6,Analytical Standards of Mebeverine hydrochloride', '', '', '', '', '', '', '', '', '', '', NULL),
(117, '4-Piperidone ethylene ketal', '', '', '', NULL, '', '', '', '177-11-7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(118, 'Furylacrylic acid', '', '', '', NULL, '', '', '', '539-47-9', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(119, 'DIHYDROCHOLESTEROL (5-Î±-cholestan-3-Î²-ol)', '', '', '', NULL, '', '', '', '80-97-7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(120, 'BENZOPHENONE IMINE ; CAS : 1013-88-3', '', '', '', NULL, '', '', '', '1013-88-3', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(121, '5-Amino-1-pentanol', '', '', '', NULL, '', '', '', '2508-29-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(122, 'Diethyl ketomalonate', '', '', '', NULL, '', '', '', '609-09-6', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(123, 'N-Methyl-4-piperidone', '', '', '', NULL, '', '', '', '1445-73-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(124, 'N-Methyl-4-hydroxypiperidine', '', '', '', NULL, '', '', '', '106-52-5', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(125, 'N-Methyl-4-chloropiperidine', '', '', '', NULL, '', '', '', '5570-77-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(126, 'N-Methyl-4-chloropiperidine HCl', '', '', '', NULL, '', '', '', '5382-23-0', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(127, 'N-Methyl-4-aminopiperidine', '', '', '', NULL, '', '', '', '41838-46-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(128, 'N-Carbethoxy-4-piperidone', '', '', '', NULL, '', '', '', '29976-53-2', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(129, 'N-Carbethoxy-4-hydroxypiperidine', '', '', '', NULL, '', '', '', '65214-82-6', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(130, 'N-Carbethoxy-4-aminopiperidine', '', '', '', NULL, '', '', '', '58859-46-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(131, 'N-Benzyl-4-piperidone', '', '', '', NULL, '', '', '', '3612-20-2', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(132, 'N-Benzyl-4-hydroxypiperidine', '', '', '', NULL, '', '', '', '4727-72-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(133, '4-Benzyl-4-hydroxypiperidine', '', '', '', NULL, '', '', '', '51135-96-7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(134, 'N-Benzyl-4-chloropiperidine', '', '', '', NULL, '', '', '', '67848-71-9', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(135, 'N-Benzyl-4-aminopiperidine', '', '', '', NULL, '', '', '', '50541-93-0', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(136, '4 - (2-Keto-benzimidozolinyl)piperidine', '', '', '', NULL, '', '', '', '20662-53-7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(137, '4-(4-Chlorophenyl)-4-hydroxypiperidine', '', '', '', NULL, '', '', '', '39512 - 49 - 7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(138, '4-(4-Bromophenyl)-4-hydroxypiperidine', '', '', '', NULL, '', '', '', '57988-58-6', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(139, '4-Phenyl-4-hydroxypiperidine', '', '', '', NULL, '', '', '', '40807 - 61 - 2', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(140, '4-Phenylpiperidine', '', '', '', NULL, '', '', '', '771 - 99 - 3', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(141, '4-Phenylpiperidine', '', '', '', NULL, '', '', '', '771 - 99 - 3', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(142, 'N-Tert Boc-4-piperidone', '', '', '', NULL, '', '', '', '79099 - 07 - 3', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(143, 'N-Boc-4-Aminopiperidine', '', '', '', NULL, '', '', '', '87120 - 72 - 7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(144, '4-Tert-Boc-aminopiperidine', '', '', '', NULL, '', '', '', '73874 - 95 - 0', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(145, 'N-Boc-4-hydroxypiperidine', '', '', '', NULL, '', '', '', '109384 - 19 - 2', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(146, '4-Piperidone HCl H2O', '', '', '', NULL, '', '', '', '40064-34-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(147, '4-Piperidone-ethylene ketal', '', '', '', NULL, '', '', '', '177 - 11 - 7', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(148, '4-hydroxypiperidine', '', '', '', NULL, '', '', '', '5382 - 16 - 1', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(149, '4-Aminopiperidine', '', '', '', NULL, '', '', '', '13035 - 19 - 3', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(150, '1-(2-Phenylethyl)piperidin-4-one', '', '', '', NULL, '', '', '', '39742-60-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(151, '1,4-Bipiperidine or 4 Piperidinopiperidine', '', '', '', NULL, '', '', '', '4897-50-1', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(152, '1,4-Bi piperidine 2 HCl', '', '', '', NULL, '', '', '', '4876-60-2', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(153, 'N-piperidin-4-yl benzamide', '', '', '', NULL, '', '', '', '33953-37-6', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(154, 'N-Isobutyl-4-piperidone', '', '', '', NULL, '', '', '', '72544-16-2', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(155, '1-(4-Chlorobenzhydryl)-piperizine', '', '', '', NULL, '', '', '', '303-26-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(156, '1,4-Bipiperidine-4-carboxamide', '', '', '', NULL, '', '', '', '39633-82-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(157, 'N-Ethyl-4-piperidone', '', '', '', NULL, '', '', '', '3612-18-8', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(158, '1,3-Dimethyl-4-piperidone', '', '', '', NULL, '', '', '', '4629-80-5', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(159, '(R)-3-aminopiperidine hydrochloride', '', '', '', NULL, '', '', '', '334618-23-4', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(160, 'N-Propyl-4-piperidone', '', '', '', NULL, '', '', '', '23133-37-1', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(161, '5-Bromo-4-chloro-3-indolyl acetate', '5-Bromo-4-chloro-3-indoxyl-3-acetate,  X-3-acetate', 'C10H7BrClNO2', '288.53', '5-Bromo-4-chloro-3-indolyl_acetate.png', 'White to beige crystalline powder', 'Min  98%', '', '3252-36-6', '', 'Max  1%', 'Store at -15Â°C, keep dry, and protect from light.', 'carbohydrates', '', '', '', '', '', '5-Bromo-4-chloro-3-indoxyl-3-acetate is a histochemical substrate for esterase.', '5-Bromo-4-chloro-3-indoxyl-3-acetate is used as X-substrate, 5-Bromo-4-chloro-3-indoxyl chromogenic substrate  Chromogenic substrate for carboxylesterase yielding a blue precipitate upon cleavage. Mainly used in histochemistry.', '', '', '', '', '', '', '', '', '', '', NULL),
(163, '5-Bromo-4-chloro-3-indolyl caprylate (X-caprylate)', 'X-caprylate ; 5-Bromo-4-chloro-3-indoxyl octanoate ; 5-BROMO-4-CHLORO-3-INDOXYL CAPRYLATE;5-BROMO-4-CHLOROINDOXYLCAPRYLATE;5-BROMO-4-CHLORO-3-INDOLYL CAPRYLATE;5-bromo-4-chloro-3-indolyl octanoate;5-BROMO-4-CHLORO-3-INDOXYL CAPRYLATE 99%;5-Bromo-4-chloro-3-indolyl caprylate (X-Caprylate)', 'C16H19BrClNO2', '372.68', '5-Bromo-4-chloro-3-indolyl_caprylate.png', 'White to off-white powder', 'Min   98%', '', '129541-42-0', '', '', 'store at -15Â°C, protect from light', 'carbohydrates', '', '55 - 60Â°C', '', '', '', '', '', '5-Bromo-4-chloro-3-indoxyl caprylate is used as X-substrate, 5-Bromo-4-chloro-3-indoxyl chromogenic substrate  Chromogenic substrate for esterase with C8 activity yielding a blue precipitate upon cleavage.', '', '', '', '', '', '', '', '', '', NULL);
INSERT INTO `products` (`id`, `name`, `synonyms`, `mf`, `mw`, `ms`, `appearance`, `purity`, `sor`, `casno`, `solubility`, `watercontent`, `storage`, `category`, `assay_by_hplc`, `melting_point`, `ph`, `dioxane_free`, `research`, `description`, `usage_product`, `application`, `identity_ir`, `identity_ftir`, `transport`, `free_phenol`, `p_nitro_phenol`, `moisture_content`, `free_inorganics`, `molar_absence`, `boiling_point`, `others`) VALUES
(164, '5-Bromo-4-chloro-3-indoxyl butyrate   (X-butyrate)', 'X-BUTYRATE;5-BROMO-4-CHLOROINDOXYLBUTYRATE;5-BROMO-4-CHLORO-3-INDOXYL BUTYRATE;5-BROMO-4-CHLORO-3-INDOLYL BUTYRATE;5-Bromo-4-chloro-3-indoxyl butyrateX-Butyrate;5-Bromo-4-chloro-(1H-indol-3-yl) butanoate;5-Bromo-4-chloro-(1H-indol-3-yl) butyrate;Butanoic acid, 5-broMo-4-chloro-1H-indol-3-yl ester', 'C12H11BrClNO2', '316.58', '5-Bromo-4-chloro-3-indoxyl_butyrate___(X-butyrate).gif', 'White to off-white powder', 'Min 98%', '', '129541-43-1', '', 'Max 0.5%', 'Store at -15Â°C, protect from light', 'carbohydrates', '', '', '', '', '', '', '', '5-Bromo-4-chloro-3-indoxyl butyrate is used as X-substrate, 5-Bromo-4-chloro-3-indoxyl chromogenic substrate  Chromogenic substrate for carboxylesterase yielding a blue precipitate upon cleavage. It has been proposed for the rapid detection of Branhamella', 'Conforms to structure', '', '', '', '', '', '', '', '', NULL),
(165, '6-Chloro-3-indolyl-Î²-D-glucuronide cyclohexylammonium salt (RED-GLUC, Rose-glucuronide CHA salt, Salmon-glucuronide CHA salt.)', 'RED-GLUC, Rose-glucuronide CHA salt, Salmon-glucuronide CHA salt. ; Salmon-beta-D-glucuronide cyclohexylammonium salt;  Salmon-Î²-D-GlcA CHX', 'C14H14ClNO7 Â· C6H13N', '442.89', '6-Chloro-3-indolyl-Î²-D-glucuronide_cyclohexylammonium_salt_(RED-GLUC__Rose-glucuronide_CHA_salt__Salmon-glucuronide_CHA_salt.).gif', 'Off-white to yellow powder', 'Min  97 %', '[Î±]20/D âˆ’70.5Â±2Â°, c = 1% in DMF/H2O 1:1', '138182-20-4', '', '', 'Store at -20Â°C.  Keep dry and protect from light.', 'carbohydrates', '', '', '', '', '', '6-Chloro-3-indoxyl-beta-D-glucuronic acid, cyclohexylammonium salt is a chromogenic Î²-glucuronidase substrate, which yields a salmon colored precipitate upon cleavage.', '', '6-Chloro-3-indoxyl-beta-D-glucuronic acid, cyclohexylammonium salt is used as Salmon substrate, 6-Chloro-3-indoxyl chromogenic substrate  Chromogenic substrate for beta-glucuronidase yielding a salm on colored precipitate upon cleavage.', '', '', '', '', '', '', '', '', '', NULL),
(166, '5-Bromo-4-chloro-3-indoxyl-beta-D-glucuronic acid, cyclohexylammonium salt monohydrate ( X-beta-D-glucuronide cyclohexylammonium salt; X-beta-D-glucuronide CHX-salt; X-beta-D-GlcA Â· CHX ; X-gluc CHA salt) ; X-gluc (CHX salt)', 'X-Glucuronide ; X-Glc ;  CHA-X-Glc ; X-GLUC CHA Salt X-GLUC CHX Salt ;', 'C14H13BrClNO7â€¢C6H13N', '521.79', '5-Bromo-4-chloro-3-indoxyl-beta-D-glucuronic_acid__cyclohexylammonium_salt_monohydrate_(_X-beta-D-glucuronide_cyclohexylammonium_salt;_X-beta-D-glucuronide_CHX-salt;_X-beta-D-GlcA_Â·_CHX_;_X-gluc_CHA_salt)_;_X-gluc_(CHX_salt).gif', 'White to off-white crystalline powder', 'Min 98%', '- 87.0 to -91.0Â°    [Î±]D.25 (c=1, DMF:H2O, 1:1)', '114162-64-0', 'Soluble in 50mg/mL in dimethylformamide', '2.5 - 4.5%', 'Shipped at Ambient Temperature. Store at +2 - 8Â°C.', 'carbohydrates', 'Min 98%', '', '', '', 'Not Intended for Diagnostic or Therapeutic Use.', 'References:  Bauer, R., et al., Functional expression of bacterial Î²-glucuronidase and its use as a reporter system in the yeast Yarrowia lipolytica.. Yeast 9, 71-75, (1993) Schmitz, U.K., et al., Application of the Î²-glucuronidase gene fusion system to Saccharomyces cerevisiae.. Curr. Genet. 17, 261-264, (1990) Daniell, H., Foreign gene expression in chloroplasts of higher plants mediated by tungsten particle bombardment. Meth. Enzymol. 217, 536-556, (1993)', 'X-Gluc is a chromogenic substrate for beta-glucuronidase (GUS) which is encoded by the gusA (uid A) gene, a widely used reporter gene. Glucuronidase cleaves X-Gluc to produce colorless glucuronic acid and an intense blue precipitate. X-Gluc is often used ', 'A chromogenic substrate for Î²-glucuronidase gene detection   XGLUC Cyclohexylammonium Salt is a Chromogenic substrate for Î²- glucuronidase (GUS) gene detection', '', 'References: 1. Jefferson RA, et al., EMBO J. 1987, 6, p3901 2. Frampton EW, et al., Food Production 1988, 51, p402 3. Watkins, et al., Environ. Microbiol. 1988, 54, p1874 4. Schmitz UK, et al., Curr. Genet. 17, 261-264, (1990) 5. Daniell H, Methods Enzymo', '', '', '', '', '', '', '', NULL),
(167, 'asd', 'asd', '', '', 'asd.png', '', '', '', 'asd', '', '', '', 'others', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(168, 'Ethyl bromopyruvate 90%', '', '', '', NULL, '', '90 %', '', '70-23-5', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(169, '3,4-Dimethoxybenzoic acid', 'DIMETHYLPROTOCATECHUIC ACID;3,4-DIMETHOXYBENZOIC ACID;AKOS 220-15;AKOS BBS-00003717;VERATRIC ACID;3,4-dimethoxy-benzoicaci;3,4-Dimethylprotocatechuic acid;3,4-dimethylprotocatechuicacid', '(CH3O)2C6H3CO2H', '182.17', '3_4-Dimethoxybenzoic_acid.gif', 'crystalline powder', 'Min 98 %', '', '93-07-2', '', '', '', 'finechemicals', '', '179-182 Â°C(lit.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(170, '3-BROMOFURAN', '', 'C4H3BrO', '146.97', '3-BROMOFURAN.png', 'Yellow to brown liquid', '97  %', '', '22037-28-1', '', '', '', 'carbohydrates', '', '', '', '', '', '1.635 g/mL at 25 Â°C', '', '', '', '', '', '', '', '', '', '', '103 Â°C', NULL),
(171, 'OCTA-O-ACETYL-B-D-MALTOSE', 'OCTA-O-ACETYL-BETA-D-MALTOSE;Octaacetyl-beta-maltose;OCTAACETYL MALTOSE;1,2,2'',3,3'',4'',6,6''-OCTA-O-ACETYL-BETA MALTOSE;4-O-(2,3,4,6-Tetra-O-acetyl-alpha-D-glucopyranosyl)-beta-D-glucopyranose tetraacetate;MALTOSE OCTAACETATE;beta-d-maltopyranose octaacetate;BETA-D-MALTOSE OCTAACETATE', 'C28H38O19', '678.59', NULL, 'White to off-white powder', 'Min 98%', '', '22352-19-8', '', '', '', 'carbohydrates', '', '159-160Â°C', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(172, 'D-Glucuronic acid', 'GLUCURONIC ACID;D-GLCA;D-GLUCURONIC ACID;Glycuronic acid ;D-GLUCURONIC ACID FREE ACID F & D &;Glucosiduronic Acid;Glucuronic Aci;(2S,3S,4S,5R,6S)-3,4,5,6-tetrahydroxyoxane-2-carboxylic acid', 'C6H10O7', '194.14', 'D-Glucuronic_acid.png', 'White to off-white crystalline powder', '', '+34.5 to +38.5Â°    [a]D20(c=1,H2O  6 hr)', '6556-12-3  (or)  18968-14-4', 'H2O: soluble100 mg/mL, clear to slightly hazy', 'Max 1%', '', 'carbohydrates', '', '159-161 Â°C(lit.)', '', '', '', '', '', '', 'confirm', '', '', '', '', '', '', '', '', NULL),
(173, '3-CHLORO-7-AZAINDOLE', '3-CHLORO-1H-PYRROLO[2,3-B]PYRIDINE;3-CHLORO-7-AZAINDOLE;1H-Pyrrolo[2,3-b]pyridine, 3-chloro-', 'C7H5clN2', '152.58', '3-CHLORO-7-AZAINDOLE.png', 'LIGHT YELLOW COLOR SOLID', 'â‰¥97%', '', '80235-01-4', 'DMSO, ETHYL ACETATE, DMF, THF', 'NMT 1.0%', '', 'finechemicals', '', '168-170', '', '', 'yes', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(174, 'Phenyl Isothiocyanate', 'ISOTHIOCYANIC ACID PHENYL ESTER PHENYL ISOTHIOCYANATE Phenyl isothiocyanate Phenyl mustard oil PHENYL ISOTHIOCYANATE PROTEIN SEQUENCING REAGENT PHENYL MUSTARD OIL PIT PITC PTC R1 THIOCARBANIL Benzene,isothiocyanato- Benzene-1-isothiocyanate Fenylisothiokyanat iso-Thiocyana-tobenaene isothiocyanato-benzen Isothiocyanatobenzene isothiocyanato-Benzene Phenyl thiocyanate', '', '', NULL, 'colourless to pale yellow liquid with a penetrating odour', '', '', '103-72-0', '', '', '', 'finechemicals', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL,
  `user_name` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `user_name`, `password`) VALUES
(1, 'sai', 'Anneboina@9');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
